// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/auth/google/callback": {
    params: {};
  };
  "/client": {
    params: {};
  };
  "/client/discover": {
    params: {};
  };
  "/client/professional/:id": {
    params: {
      "id": string;
    };
  };
  "/client/booking/:id/pay": {
    params: {
      "id": string;
    };
  };
  "/client/packages": {
    params: {};
  };
  "/client/messages": {
    params: {};
  };
  "/client/payments": {
    params: {};
  };
  "/client/notifications": {
    params: {};
  };
  "/professional": {
    params: {};
  };
  "/professional/agenda": {
    params: {};
  };
  "/professional/clients": {
    params: {};
  };
  "/professional/services": {
    params: {};
  };
  "/professional/availability": {
    params: {};
  };
  "/professional/payments": {
    params: {};
  };
  "/professional/messages": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/payments": {
    params: {};
  };
  "/session/:id": {
    params: {
      "id": string;
    };
  };
  "/session/:id/rating": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/auth/google/callback" | "/client" | "/client/discover" | "/client/professional/:id" | "/client/booking/:id/pay" | "/client/packages" | "/client/messages" | "/client/payments" | "/client/notifications" | "/professional" | "/professional/agenda" | "/professional/clients" | "/professional/services" | "/professional/availability" | "/professional/payments" | "/professional/messages" | "/admin" | "/admin/users" | "/admin/payments" | "/session/:id" | "/session/:id/rating";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/auth.google.callback.tsx": {
    id: "routes/auth.google.callback";
    page: "/auth/google/callback";
  };
  "routes/client/_layout.tsx": {
    id: "routes/client/_layout";
    page: "/client" | "/client/discover" | "/client/professional/:id" | "/client/booking/:id/pay" | "/client/packages" | "/client/messages" | "/client/payments" | "/client/notifications";
  };
  "routes/client/dashboard.tsx": {
    id: "routes/client/dashboard";
    page: "/client";
  };
  "routes/client/discover.tsx": {
    id: "routes/client/discover";
    page: "/client/discover";
  };
  "routes/client/professional.$id.tsx": {
    id: "routes/client/professional.$id";
    page: "/client/professional/:id";
  };
  "routes/client/booking.$id.pay.tsx": {
    id: "routes/client/booking.$id.pay";
    page: "/client/booking/:id/pay";
  };
  "routes/client/packages.tsx": {
    id: "routes/client/packages";
    page: "/client/packages";
  };
  "routes/client/messages.tsx": {
    id: "routes/client/messages";
    page: "/client/messages";
  };
  "routes/client/payments.tsx": {
    id: "routes/client/payments";
    page: "/client/payments";
  };
  "routes/client/notifications.tsx": {
    id: "routes/client/notifications";
    page: "/client/notifications";
  };
  "routes/professional/_layout.tsx": {
    id: "routes/professional/_layout";
    page: "/professional" | "/professional/agenda" | "/professional/clients" | "/professional/services" | "/professional/availability" | "/professional/payments" | "/professional/messages";
  };
  "routes/professional/dashboard.tsx": {
    id: "routes/professional/dashboard";
    page: "/professional";
  };
  "routes/professional/agenda.tsx": {
    id: "routes/professional/agenda";
    page: "/professional/agenda";
  };
  "routes/professional/clients.tsx": {
    id: "routes/professional/clients";
    page: "/professional/clients";
  };
  "routes/professional/services.tsx": {
    id: "routes/professional/services";
    page: "/professional/services";
  };
  "routes/professional/availability.tsx": {
    id: "routes/professional/availability";
    page: "/professional/availability";
  };
  "routes/professional/payments.tsx": {
    id: "routes/professional/payments";
    page: "/professional/payments";
  };
  "routes/professional/messages.tsx": {
    id: "routes/professional/messages";
    page: "/professional/messages";
  };
  "routes/admin/_layout.tsx": {
    id: "routes/admin/_layout";
    page: "/admin" | "/admin/users" | "/admin/payments";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/admin";
  };
  "routes/admin/users.tsx": {
    id: "routes/admin/users";
    page: "/admin/users";
  };
  "routes/admin/payments.tsx": {
    id: "routes/admin/payments";
    page: "/admin/payments";
  };
  "routes/session.$id.tsx": {
    id: "routes/session.$id";
    page: "/session/:id";
  };
  "routes/session.$id.rating.tsx": {
    id: "routes/session.$id.rating";
    page: "/session/:id/rating";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/auth.google.callback": typeof import("./app/routes/auth.google.callback.tsx");
  "routes/client/_layout": typeof import("./app/routes/client/_layout.tsx");
  "routes/client/dashboard": typeof import("./app/routes/client/dashboard.tsx");
  "routes/client/discover": typeof import("./app/routes/client/discover.tsx");
  "routes/client/professional.$id": typeof import("./app/routes/client/professional.$id.tsx");
  "routes/client/booking.$id.pay": typeof import("./app/routes/client/booking.$id.pay.tsx");
  "routes/client/packages": typeof import("./app/routes/client/packages.tsx");
  "routes/client/messages": typeof import("./app/routes/client/messages.tsx");
  "routes/client/payments": typeof import("./app/routes/client/payments.tsx");
  "routes/client/notifications": typeof import("./app/routes/client/notifications.tsx");
  "routes/professional/_layout": typeof import("./app/routes/professional/_layout.tsx");
  "routes/professional/dashboard": typeof import("./app/routes/professional/dashboard.tsx");
  "routes/professional/agenda": typeof import("./app/routes/professional/agenda.tsx");
  "routes/professional/clients": typeof import("./app/routes/professional/clients.tsx");
  "routes/professional/services": typeof import("./app/routes/professional/services.tsx");
  "routes/professional/availability": typeof import("./app/routes/professional/availability.tsx");
  "routes/professional/payments": typeof import("./app/routes/professional/payments.tsx");
  "routes/professional/messages": typeof import("./app/routes/professional/messages.tsx");
  "routes/admin/_layout": typeof import("./app/routes/admin/_layout.tsx");
  "routes/admin/dashboard": typeof import("./app/routes/admin/dashboard.tsx");
  "routes/admin/users": typeof import("./app/routes/admin/users.tsx");
  "routes/admin/payments": typeof import("./app/routes/admin/payments.tsx");
  "routes/session.$id": typeof import("./app/routes/session.$id.tsx");
  "routes/session.$id.rating": typeof import("./app/routes/session.$id.rating.tsx");
};